### ISSUE TITLE
Socket closed error 3 after first connect

### ISSUE THREAD

**Issue by PanickingLynx** [RouHim/beammp-container-image#29] opened 2023-05-02 20:08 UTC
After connecting to the server once, me and my friends can't seem to connect to it any further.

The server log shows:
```
[2023/05/02 20:06:42.911] Identify [INFO] Identifying new ClientConnection...
[2023/05/02 20:06:43.143] Identify [DEBUG] Name -> PanickingLynx, Guest -> 0, Roles -> USER
```

But the game states `"Disconnected Socket Closed Code 3"`
This issue has not occurred to me before so I don't really know where to start and I can't find anything about it.

Any ideas as to what might have gone wrong? It's like you can only connect for the first minute of uptime or so, to then connect after, the container network has to be restarted.

**Comment by RouHim** [comment] 2023-05-03 06:14
Oof that's not so great of course and I can't reproduce it on the fly either, are you using any mods? If so try it without.
For me it's hard to say if it's me or the beammp server (which I do not maintain).

**Comment by PanickingLynx** [comment] 2023-05-03 06:19
It's the same issue with and without mods sadly :(
Yeah I wasn't sure either if it is your Docker image or the bmp Server but it could also be my systemconfig or other stuff I've messed up.
Just wanted to hear if you might have already been aware of an issue in this direction.

**Comment by RouHim** [comment] 2023-05-03 06:22
Tbh not played much recently but for me it looks like they are already fixing the issue (linked issue).

**Comment by ashmaker000** [comment] 2023-05-10 06:50
I'm currently having this issue with all 14 of my servers.
What I've noticed is people will join and once they are done they leave which then freezes the server and is in accessible unless you restart the server (or docker container) but then you still have the same issue,
I've noticed the "latest" build is pointing to v3.2.0, is there anyway to revert back to v3.1.1?

Screenshots from my console:
![image](https://github.com/RouHim/beammp-container-image/assets/8276382/50778e23-bfb8-4124-8609-62f4839ac8b9)
![image](https://github.com/RouHim/beammp-container-image/assets/8276382/d604c6ac-585b-46da-b9ea-cbed870f8787)
![image](https://github.com/RouHim/beammp-container-image/assets/8276382/72705262-0e99-4211-a947-b1865d9d9b35)
![image](https://github.com/RouHim/beammp-container-image/assets/8276382/75af6f75-b7f5-41aa-8b1e-aa99ea1618d0)
![image](https://github.com/RouHim/beammp-container-image/assets/8276382/e18022f9-4174-47a5-9d3a-3dd896c5d4b4)

**Comment by RouHim** [comment] 2023-05-10 07:22
It would be great if you could help me with the error analysis. You can try to use the beammp server directly instead of the docker container. If the error does not occur, we know that it is the container (which I would find very strange). An older version makes no sense at this point, because it would not work with the latest version of the client.

As I mentioned earlier, there is a problem with beammp server itself that I mentioned in the previous post. This ticket is also still open.

What you could try is to use the "unstable" tag instead of the "latest" version of my container. This is based on the master branch and **may** contain the fix already.

**Comment by ashmaker000** [comment] 2023-05-10 08:21
Unable to use Unstable as Set_option is failing in the BeamMP git code:
![image](https://github.com/RouHim/beammp-container-image/assets/8276382/7264acbd-c086-47bb-af56-264735565f0c)

I have however just tested your next tag and thats working fine for me

![image](https://github.com/RouHim/beammp-container-image/assets/8276382/c63a325c-2ab6-4375-bdbf-09cdafc06f8e)

**Comment by RouHim** [comment] 2023-05-10 08:28
I'm going for a manual build for the latest tag, give me a sec. Would be awesome if you could test it.

**Comment by ashmaker000** [comment] 2023-05-10 08:28
Sure let me know when its up and I'll do a pull request

**Comment by RouHim** [comment] 2023-05-10 08:32
Only as a technical side note for people who are interested. I currently use the podman stack to build a container image and push it to dockerhub. This seems to be causing increasing problems. So i will most likely switch back to the docker stack....

**Comment by RouHim** [comment] 2023-05-10 08:59
@ashmaker000 Updated the latest image, can you please try it?

**Comment by ashmaker000** [comment] 2023-05-10 09:23
Just pushed this down to 4 servers and all 4 still have the same issue.
I click quit and the server stops responding:
![image](https://github.com/RouHim/beammp-container-image/assets/8276382/6c969eb6-aa72-4312-8390-3874bc0e1881)

**Comment by RouHim** [comment] 2023-05-10 10:13
Ok, thanks for testing, just pushed a new version of the "latest" tag. If this still does not work, this will not be a quick fix sadly.

**Comment by ashmaker000** [comment] 2023-05-10 10:14
Give me 30 minutes I'll test again

**Comment by ashmaker000** [comment] 2023-05-10 10:23
> Ok, thanks for testing, just pushed a new version of the "latest" tag. If this still does not work, this will not be a quick fix sadly.

Bad news...
Its still doing the same thing and freezes the server

**Comment by RouHim** [comment] 2023-05-10 11:00
Ok :/ what is the easiest way to reproduce the problem?

**Comment by ashmaker000** [comment] 2023-05-10 11:26
I'll give you my specs:

Mint OS

Docker:
Client:
 Version:           20.10.21
 API version:       1.41
 Go version:        go1.18.1
 Git commit:        20.10.21-0ubuntu1~20.04.2
 Built:             Thu Apr 27 05:56:19 2023
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.21
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.1
  Git commit:       20.10.21-0ubuntu1~20.04.2
  Built:            Thu Apr 27 05:37:01 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.5.9-0ubuntu1~20.04.6
  GitCommit:        
 runc:
  Version:          1.1.0-0ubuntu1~20.04.2
  GitCommit:        
 docker-init:
  Version:          0.19.0
  GitCommit:        


Using Portainer UI to mange - Verison 2.18.2

Its definitely something on BeamMP 3.2.0 as ive gone back to your old build "next" and again its working fine which is BeamMP 3.1.1

**Comment by RouHim** [comment] 2023-05-10 11:56
This means you start the server, all is well and after a certain?!? time, the server is ready to go. time you can no longer join the server?

**Comment by ashmaker000** [comment] 2023-05-10 13:04
So I start the server, join it and play for example, then when press quit and I leave, the server freeze up and isnt accessible anymore which also makes it disappear from the server list so the back end is seeing it as offline.

**Comment by RouHim** [comment] 2023-05-10 13:06
Thanks, I'll have to dig into it. I'll keep you up-to-date.

**Comment by ashmaker000** [comment] 2023-05-10 13:07
Amazing thanks,
If you need me to test anything just @ me and I'll test as soon as I can

**Comment by RouHim** [comment] 2023-05-11 07:32
Oh damn, I think I found the problem and nobody says anything :P The "latest" container is running on version 3.2 of the beammp server which is explicitly marked as unstable. But the latest stable version is 3.1.1. I'll adjust it and get back to you...

**Comment by RouHim** [comment] 2023-05-11 07:58
Ok, just pushed the update. Hopefully this fixes now the problem.

**Comment by ashmaker000** [comment] 2023-05-11 08:06
Just pushed it to one of the servers,
Haven't had the issue yet and ive gone in and out of it a few times now so its looking promising! 
Thanks for sorting that out!

**Comment by RouHim** [comment] 2023-05-11 09:49
@PanickingLynx can you also please test if it now works for you?

**Comment by PanickingLynx** [comment] 2023-05-11 10:45
@RouHim Will do when I'm at Home! :) 
Berufsschule ;)

**Comment by RouHim** [comment] 2023-05-11 10:57
Dann schön aufpassen ;)

**Comment by ashmaker000** [comment] 2023-05-11 11:00
> Dann schön aufpassen ;)
> 
> @ashmaker000 thank you very much for that much testing

No problem at all! Cheers for fixing!

**Comment by PanickingLynx** [comment] 2023-05-12 06:25
So everything seems in order so far :)
Thanks for the Work :)

**Comment by RouHim** [comment] 2023-05-12 06:34
Awesome, thank you :)

**Closed** 2023-05-12 06:34 UTC
Labels: bug
