### ISSUE TITLE
Latest pull broke servers

### ISSUE THREAD

**Issue by ashmaker000** [RouHim/beammp-container-image#50] opened 2024-01-10 10:07 UTC
Hey there,

I've just updated my images to the latest version and since doing that I'm now getting "terminate called without an active exception
Aborted (core dumped)" in the logs and the servers are not showing up on the list,

are you able to see if its an issue with the docker image please?

![image](https://github.com/RouHim/beammp-container-image/assets/8276382/5446c997-02ef-4c08-a7cd-132f0d5df81c)

**Comment by ashmaker000** [comment] 2024-01-10 23:21
@RouHim Any chance you've been able to look at this?

**Comment by RouHim** [comment] 2024-01-11 05:36
Could you please try to start the server without the mods, and check if the error persists?

**Comment by RouHim** [comment] 2024-01-11 07:58
I also did an update, that hopefully fixes this issue.

**Comment by ashmaker000** [comment] 2024-01-11 08:01
![image](https://github.com/RouHim/beammp-container-image/assets/8276382/e229c3ce-845b-4811-9040-5400c04989e3)


Looks like it started to run after removing the modes, but this has happened to 29 servers if mine,

Oh nice has that been pushed out on Docker Hub as it still says 2 days ago last updated?

**Comment by RouHim** [comment] 2024-01-11 08:38
Ok, let's see, the update is still compiling, but should be public in about 2 hours.

**Comment by ashmaker000** [comment] 2024-01-11 08:40
Ok great I'll keep an eye out, thanks

**Comment by ashmaker000** [comment] 2024-01-11 11:49
Unfortunately this hasn't fixed the issue, im still having the same issue.
![image](https://github.com/RouHim/beammp-container-image/assets/8276382/38af7a80-4970-4e64-abec-376409f6921d)


Whats the best way to send you one of the core dump file?

**Comment by RouHim** [comment] 2024-01-11 12:05
Tbh, for me it looks like there is an corrupted mod.

**Comment by ashmaker000** [comment] 2024-01-11 12:11
Let me do some more troubleshooting and see what I can find, but from what im seeing now its a mod in the server side folder

**Comment by ashmaker000** [comment] 2024-01-12 09:14
So its something with Cobalt Essentials that the latest pull didn't like, not sure why but I've messaged Dudekahdron about it.

**Comment by RouHim** [comment] 2024-01-13 10:35
Ok, should we keep this issue open or do you want to close it?

**Comment by ashmaker000** [comment] 2024-01-13 16:30
> Ok, should we keep this issue open or do you want to close it?

Well im not sure, Lion sent me a docker file that seemed to work with the plugins like Cobalt Essentials and Infection for example so not entirely sure where the issue is.

**Comment by RouHim** [comment] 2024-01-13 17:26
Ok then the problem is probably not solved, then we'll leave the ticket open. Maybe @lionkor  could help me how I could improve the debug output when I compile myself, currently I do it this way:
```bash
[...]
RUN cmake . -B bin \
    -DCMAKE_TOOLCHAIN_FILE=./vcpkg/scripts/buildsystems/vcpkg.cmake \
    -DCMAKE_BUILD_TYPE=Release

# Build the 'BeamMP-Server' executable
RUN cmake --build bin --parallel -t BeamMP-Server
RUN strip bin/BeamMP-Server
[...]
```

I assume that among other things the strip command is not so good correct?

**Comment by lionkor** [comment] 2024-01-15 00:16
The strip is fine, it should already strip it for you since its a release build. Not really sure where the issue is to be honest. You can use and run the files in scripts/ (though there is no alpine one, but you can read them and see). They produce very optimized versions of the server, with some space reduction stuff, but they also take forever to build.

**Comment by lionkor** [comment] 2024-01-15 00:16
Best would still be to use official builds probably

**Comment by RouHim** [comment] 2024-01-15 06:06
> Best would still be to use official builds probably

Jep I already implemented it on a feature branch. When you are shipping arm64 images with the official releases, let me know, I'll do the switch to your compiled binaries.

**Comment by lionkor** [comment] 2024-01-15 13:44
Next release coming soon has arm64 builds

**Comment by ashmaker000** [comment] 2024-01-15 13:51
If you need any testing from my end let me know

**Comment by RouHim** [comment] 2024-01-15 13:53
Spoiler, there will be breaking changes.

**Comment by ashmaker000** [comment] 2024-01-15 15:28
> @ashmaker000 Not live yet but this will change: https://github.com/RouHim/beammp-container-image/tree/51-update-to-new-envs-and-official-builds#%EF%B8%8F-breaking-change-and-migration-guide-%EF%B8%8F

Ok thanks I'll get things ready to change them values

**Comment by RouHim** [comment] 2024-01-15 18:58
@ashmaker000 Ping, It's done

**Comment by ashmaker000** [comment] 2024-01-15 22:22
> @ashmaker000 Ping, It's done

I'll test this tomorrow morning and will let you know

**Comment by ashmaker000** [comment] 2024-01-16 08:02
So have tested by creating a fresh pull request.
Works fine if I dont have mods in the server folder, when I add them it crashes and spits out this error:
![Screenshot 2024-01-16 075427](https://github.com/RouHim/beammp-container-image/assets/8276382/65ef8c56-ccb3-4eeb-b60d-e68f510a7f19) which to me looks like a windows directory format

So if I delete CE but have Outbreak in there I get this error:
![Screenshot 2024-01-16 075647](https://github.com/RouHim/beammp-container-image/assets/8276382/f17d653f-803e-4163-9d5e-3fbbdd5ff639)

When removing CE and Outbreak it seems to be happy

![image](https://github.com/RouHim/beammp-container-image/assets/8276382/fbce9e65-525f-4e43-a3ba-96681c6d3381)

I tried with 2 other mods BeamTraffic and Lava/Acid flood and it seems to have worked with them:
![image](https://github.com/RouHim/beammp-container-image/assets/8276382/9ea3b0fa-6bcb-4161-b1f6-3ed88de4ac44)


Confused why its not working with CE and Outbreak though

**Comment by ashmaker000** [comment] 2024-01-16 08:39
Yeah perms are correct as its seeing the other plugins when they are added

**Comment by RouHim** [comment] 2024-01-16 08:42
Don't be so sure, it may well be that this mod wants to write data and the other mods do not, make a chmod -R 777 on the server mods folder to be on the safe side.

**Comment by ashmaker000** [comment] 2024-01-16 08:52
So just ran that, now the server has a heartbeat, but im confused why all of a sudden this stopped working when no permissions were changed, and also how it worked with Lions version but any way Im happy to have this closed if you want

Thanks for helping get this sorted :)

**Closed** 2024-01-16 08:54 UTC
Labels: bug
